name: Java CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package
      working-directory: OtmTodoApp-master/OtmTodoApp-master
    
    - name: Copy JAR to root for Docker
      run: |
        mkdir -p target
        cp OtmTodoApp-master/OtmTodoApp-master/target/*.jar target/
    
    - name: Build Docker image
      run: docker build -t todoapp:${{ github.sha }} .
    
    - name: Test Docker image
      run: |
        docker run --rm todoapp:${{ github.sha }} --version || echo "Docker image built successfully"
    
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: target/*.jar
